// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Science.DB;

#nullable disable

namespace Science.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240809065248_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Science.DB.AdminUser", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Science.DB.Article", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("ArticleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsScopus")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWoS")
                        .HasColumnType("boolean");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<ScopusData>("ScopusData")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<WoSData>("WoSData")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
